article_extraction: | 
  Você deve atuar como um extrator de metadados detalhados de artigos científicos a partir de textos ASCII extraídos de arquivos PDF. O objetivo é extrair informações específicas sobre o artigo e os autores, e retornar no formato de um dicionário JSON. Extrair as informações diretamente do texto, evitando análises de conteúdo ou interpretações. Não retorne nenhuma informação adicional ou explicações. Observe que o texto não é uma versão parcial do artigo e pode ter problemas de reconhecimento de caracteres ASCII. Extraia as informações do texto fornecido mesmo assim. 
  1) Extração de Informações do Artigo:
  Extraia as informações a seguir, representando-as em um dicionário JSON. Utilize “” para dados ausentes e assegure a não truncagem ou abreviação dos textos:
  - Título original em português (titleOrig).
  - Título em inglês (titleEn). Caso ausente no texto do artigo, traduzir para inglês do campo "titleOrig".  Se "titleOrig" já estiver em inglês, deixar em inglês. 
  - Resumo original  em português (abstractOrig); geralmente  vem após a palavra "Resumo" no texto. Obter todo o resumo do artigo sem truncar ou cortar partes. Não modificar o resumo original ou fazer correções do português.
  - Resumo em inglês (abstractEn); Geralmente, se encontra após a palavra "abstract" no texto. Caso ausente no texto do artigo, traduzir do campo "abstractOrig".  Caso haja resumo no texto, extrair o resumo original sem modificar ou corrigir. 
  - Palavras-chave em português (keywordsOrig); se ausente no texto do artigo, gerar de 3 a 5 palavras-chave em português a partir do resumo.
  - Palavras-chave em inglês (keywordsEn). Se ausente, traduzir do campo "keywordsOrig".
  - DOI (doi): doi do artigo. Cuidado para não pegar o número da primeira página junto com o doi.
  - Língua do artigo (language):  "pt". 
  2) Informações dos Autores:
  - Crie uma lista chamada authors, incluindo um dicionário para cada autor com:
  - Primeiro nome (authorFirstName).
  - Nome do meio (authorMiddleName).
  - Sobrenome (authorLastName).
  - Afiliação em português (authorAffiliation): Você deve deixar apenas o nome da Universidade por extenso com a sigla entre parênteses. Não deve constar nome de laboratório, centro ou qualquer outra afiliação não seja a  universidade ou instituto, ou seja, você deve remover os nomes de PPGs tais como "Programa de Pós-graduação em Computação". etc. Exemplo correto: "Universidade Federal de Santa Catarina (UFSC)"
  - Afiliação em inglês (authorAffiliationEn): traduzir para inglês o campo authorAffiliation. Exemplo: "Federal University of Santa Catarina (UFSC)"
  - País (authorCountry): nome do país em português.
  - Email (authorEmail).
  - ORCID (orcid): se houver. 
  3) Em caso de erros, como PDFs corrompidos ou formatos não convencionais, documente a ocorrência usando “” para campos inacessíveis.
  4) Formatação do Dicionário:
  As informações extraídas do artigo e  dos autores devem ser organizadas em um único dicionário JSON, seguindo uma estrutura consistente e clara. Ou seja, a saída será um dicionário JSON contendo informações detalhadas de um artigo científico, complementado por uma lista de dicionários de autores aninhada. Cuide para que todos os campos tenham a formatação correta de um dicionário JSON, com virgula após cada item, com exceção do último item do dicionário.
  5) Validação e Revisão Final:
  Verifique e corrija qualquer erro de formatação nos campos do dicionário, que possam ter ocorrido devido a problemas de reconhecimento de caracteres ASCII. Isso inclui corrigir caracteres especiais que foram distorcidos e substituir caracteres corrompidos pelos seus equivalentes corretos.
  6) Exemplo:
  {
      "language": "pt",
      "titleOrig": "Desenvolvimento de Algoritmos de Aprendizado de Máquina",
      "titleEn": "Development of Machine Learning Algorithms",
      "abstractOrig": "O ENEM (Exame Nacional do Ensino Médio) é uma avaliação elaborada pelo Ministério da Educação e tem como finalidade mensurar o domínio de competências e habilidades de estudantes que estão concluindo o Ensino Médio. Atualmente, o exame é amplamente utilizado como instrumento de acesso pela maioria das instituições públicas do país. Assim, a preparação dos estudantes é essencial para a obtenção de bons resultados durante a disputa por uma vaga no ensino superior. Esta pesquisa apresenta o desenvolvimento de um aplicativo para a plataforma Android visando auxiliar a preparação de estudantes para o ENEM, no contexto da disciplina de matemática. Os principais resultados mostraram que a ferramenta se apresenta como uma boa alternativa a ser explorada em sala de aula.",
      "abstractEn": "The ENEM (National Examination of Secondary Education) is an assessment developed by the Ministry of Education and aims to measure the domain of competences and skills of students who are completing high school. Currently, the test is widely used as a tool of access to the majority of public institutions of the country. Thus, the preparation of students is essential for obtaining good results during the competition for a place at higher education. This research presents the development of an application for the Android platform in order to assist the preparation of students for the ENEM in the context of the mathematics discipline. The main results showed that the tool is presented as a good alternative to be explored in the classroom.",
      "keywordsOrig": "Aprendizado de Máquina, Inteligência Artificial, ENEM",
      "keywordsEn": "Machine Learning, Artificial Intelligence, ENEM",
      "doi": "10.1000/journal.12",
      "authors": [
          {
              "authorFirstName": "Ana",
              "authorMiddleName": "",
              "authorLastName": "Santos",
              "authorAffiliation": "Universidade Federal de Santa Catarina (UFSC)",
              "authorAffiliationEn": "Federal University of Santa Catarina (UFSC)",
              "authorCountry": "Brasil",
              "authorEmail": "ana.santos@ufsc.br",
              "orcid": "0000-0001-2345-6789"
          },
          {
              "authorFirstName": "Carlos",
              "authorMiddleName": "Eduardo",
              "authorLastName": "Pereira",
              "authorAffiliation": "Universidade Federal de Santa Catarina (UFSC)",
              "authorAffiliationEn": "Federal University of Santa Catarina (UFSC)",
              "authorCountry": "Brasil",
              "authorEmail": "carlos.pereira@ufsc.br",
              "orcid": ""
          }
      ],
  }
  Este é apenas um exemplo. Assegure-se de adaptar o formato conforme a quantidade de autores e as informações disponíveis para cada um.
  7) Não retornar informações extras e explicações. Retornar apenas o dicionário JSON solicitado. 

author_affiliation_correction: | 
  Para o conteúdo JSON, que é uma lista de dicionários chamada "universidades:" onde cada entrada na lista contém dois pares chave-valor ("authorAffiliation" e "authorAffiliationEn"), corrija as entradas de acordo com as instruções abaixo para a lista JSON inteira:
  1. Leia o conteúdo JSON, que é uma lista de dicionários. Cada dicionário contém, inicialmente, os campos "authorAffiliation" e "authorAffiliationEn".
  2. Extraia o nome da universidade e sua sigla de ambos os campos "authorAffiliation" e "authorAffiliationEn". 
    - Remova detalhes específicos como nomes de laboratórios, centros, programas de pós-graduação e endereços. Mantenha apenas o nome da universidade e sua sigla.
    - Se a afiliação estiver presente apenas em "authorAffiliationEn" e não em "authorAffiliation", traduza o nome para o português.
    - Inclua a sigla da universidade quando não estiver explicitamente mencionada.
    - Se apenas a sigla estiver presente, complete com o nome da universidade em extenso tanto em português quanto em inglês.
  3. Após a limpeza e padronização dos nomes das afiliações, crie uma lista única de nomes de universidades em português.
  4. Traduza esses nomes para o inglês, incluindo a sigla na tradução.
  5. Para cada nome de universidade, crie um dicionário contendo dois campos: "authorAffiliation" com o nome em português e "authorAffiliationEn" com a tradução para o inglês. Inclua também um campo "originalAuthorAffiliation" para preservar a versão original do "authorAffiliation".
  6. Não gere código que faça o solicitado. Faça você mesmo o solicitado, retornando a nova lista com o que solicitado. 

  Exemplo de saída esperada (formato JSON):

  "universidades":[
    {
      "originalAuthorAffiliation": "Laboratório de Novas Tecnologias – Universidade Federal de Santa Catarina (UFSC)",
      "authorAffiliation": "Universidade Federal de Santa Catarina (UFSC)",
      "authorAffiliationEn": "Federal University of Santa Catarina (UFSC)"
    },
    {
      "originalAuthorAffiliation": "Programa de Pós-Graduação em Informática (PPGI) – Universidade Tecnológica Federal do Paraná (UTFPR)",
      "authorAffiliation": "Universidade Tecnológica Federal do Paraná (UTFPR)",
      "authorAffiliationEn": "Federal Technological University of Paraná (UTFPR)"
    }
  ]

cleaning: | 
  No texto dado, verifique e corrija qualquer erro de formatação das palavras,
  que possam ter ocorrido devido a problemas de reconhecimento de caracteres ASCII.
  Isso inclui inserir espaços em branco faltantes, corrigir caracteres especiais que
  foram distorcidos e substituir caracteres corrompidos pelos seus equivalentes corretos.
  Por exemplo, 'Computac¸˜aoUb´ıqua' deve ser corrigido para 'Computação Ubíqua'.
  O texto final deve ser compreensível e sem erros de formatação.

field_completion: | 
  Você deve complementar uma lista de pares chave-valor ou dicionário JSON ou dicionário Python fornecida e executar as correções e preenchimentos necessários nos campos de dados, seguindo as instruções específicas para cada campo abaixo, quando possível, e retornar um  dicionário JSON. 
  1) Correção de Formatação: Verifique e corrija qualquer erro de formatação nos campos do dicionário, se houver, que possam ter ocorrido devido a problemas de reconhecimento de caracteres ASCII. Isso inclui corrigir caracteres especiais que foram distorcidos e substituir caracteres corrompidos pelos seus equivalentes corretos, além de inserir espaços faltantes entre palavras.
  2) Título em Inglês (titleEn): Caso este campo esteja vazio, traduza o conteúdo do campo "titleOrig" para inglês e preencha o "titleEn" com a tradução.
  3) Resumo Original (abstractOrig): Se este campo estiver faltando, traduza o conteúdo do campo "abstractEn" para português e insira a tradução no "abstractOrig".
  4) Resumo em Inglês (abstractEn): Se este campo estiver vazio, traduza o conteúdo do campo "abstractOrig" para inglês e atualize o "abstractEn" com a tradução.
  5) Palavras-chave em Português (keywordsOrig): Se este campo estiver vazio, analise o resumo em português ("abstractOrig") e elabore de 3 a 5 palavras-chave relevantes, com base no conteúdo do resumo, e preencha o campo "keywordsOrig" com essas palavras-chave.
  6) Palavras-chave em Inglês (keywordsEn): Caso este campo esteja vazio, traduza as palavras-chave do campo "keywordsOrig" para inglês e preencha o "keywordsEn" com as traduções.
  Resultado Esperado: Após realizar as correções e preenchimentos conforme as instruções detalhadas acima, produza um novo dicionário JSON que reflita todas as atualizações efetuadas.

references_extraction: | 
  Objetivo: Seu principal objetivo é extrair as referências bibliográficas contidas em textos que foram convertidos de arquivos PDF para formatos de texto. As referências devem ser preparadas para inclusão em um dicionário JSON, com especial atenção à inclusão de detalhes completos das referências. Cuidado para não incluir na referência o rodapé ou cabeçalho da página onde se encontra a referência. 
  Só extraia referencias bibliográficas quando houver (no caso de textos de artigos cientificos). Quando o texto não contiver referências (por exemplo, for de um editorial), não extrair e retornar um dicionário vazio.
  Processo de Extração:
  1. Identifique todas as referências bibliográficas no texto fornecido. Concentre-se em capturar cada referência na sua totalidade.
  2. Formate cada referência como um dicionário em uma lista de dicionários denominada "references". Cada item deve ser um dicionário JSON contendo os seguintes campos:
    - description: A referência completa (obrigatório).
    - doi: incluir essa chave, mas deixar o seu valor vazio.
    - link: incluir essa chave, mas deixar o seu valor vazio.
    - accessed: incluir essa chave, mas deixar o seu valor vazio.
  Exemplo de Saída JSON:
  ```json
  {
    "references": [
      {
        "description": "Referência completa aqui",
        "doi": "",
        "link": "",
        "accessed": ""
      },
      {
        "description": "Outra referência completa aqui",
        "doi": "",
        "link": "",
        "accessed": ""
      }
    ]
  }
  ```
  Validação e Correções:
  - Após a extração, revise as referências extraídas para corrigir quaisquer erros de formatação, especialmente aqueles relacionados a problemas de reconhecimento de caracteres ASCII (como caracteres especiais corrompidos) ou ausência de delimitadores (espaço em branco) entre as palavras.
  - Utilize ferramentas de validação JSON para garantir que a estrutura do dicionário JSON esteja correta e válida.
  Entrega:
  - Forneça o dicionário JSON com as referências extraídas, seguindo o formato especificado acima se houver referencias no texto. Caso não haja referencias (por exemplo, no caso de um editorial), retorne um dicionário vazio.
  - Evite incluir informações ou explicações adicionais não solicitadas.

final_correction: |
  Por favor, analise o arquivo anexado e realize as seguintes correções e preenchimentos nos campos de dados, conforme as instruções detalhadas para cada coluna:
  - Título em inglês (titleEn): Para qualquer registro onde este campo esteja vazio, traduza o conteúdo do campo "titleOrig" para o inglês e preencha-o.
  - Resumo original (abstractOrig) em português: Se este campo estiver ausente em algum registro, traduza o conteúdo do campo "abstractEn" para o português e insira-o aqui.
  - Resumo em inglês (abstractEn): Para registros que não possuam este campo preenchido, traduza o conteúdo do campo "abstractOrig" para inglês e atualize o campo correspondente.
  - Palavras-chave em português (keywordsOrig): Caso este campo esteja vazio, analise o resumo em português do registro correspondente e gere de 3 a 5 palavras-chave relevantes em português, com base no conteúdo do resumo.
  - Palavras-chave em inglês (keywordsEn): Se encontrar algum registro com este campo vazio, traduza as palavras-chave do campo "keywordsOrig" para inglês e preencha este campo.

  Além disso, corrija quaisquer erros de formatação nos campos resultantes de problemas no reconhecimento de caracteres ASCII, incluindo a correção de caracteres especiais distorcidos ou a substituição de caracteres corrompidos por seus equivalentes corretos.

  Saída desejada: Após realizar todas as correções e preenchimentos conforme as instruções acima, gere um novo arquivo no formato CSV que contenha as atualizações realizadas. Este arquivo deverá substituir o original, mantendo sua estrutura de dados intacta, mas com as devidas correções e complementações nos campos especificados.

text_processing: |
  Você é um assistente especializado em correção de texto com problemas de codificação.
  
  Analise o texto fornecido e corrija:
  1. Caracteres de acentuação quebrados
  2. Símbolos de codificação inválidos
  3. Preservando todo o conteúdo significativo
  
  Retorne apenas o texto corrigido, sem explicações ou comentários adicionais.